language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸시 될 때 수행할지 설정
# 현재 옵션은 오직 master 브랜치에 push 될 때만 수행
branches:
  only:
    - master

# Travis CI 서버의 Home
# gradle을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여 같은 의존성은 다음 배포 때부터 다시 받지 않도록 함
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시 되었을 때 수행하는 명령
# 여기서는 프로젝트 내부의 gradlew를 통해 clean & build 를 수행
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
# Travis CI 실행 완료 시 자동으로 알람이 가도록 설정
notifications:
  email:
    recipients:
      - junghyen2003@gmail.com
