# CodeDeploy 버전
# 프로젝트 버전이 아니므로 0.0 이외에 다른 버전을 사용하면 오류가 발생
version: 0.0
os: linux
files:
    # CodeDeploy에서 전달해준 파일 중 destination으로 이동 시킬 대상을 지정
    # 루트경로(/)의 경우 전체 파일
  - source: /
    # source에서 지정된 파일을 받을 위치
    # 이후 Jar 실행 등은 destination에서 옮긴 파일들로 진행
    destination: /home/ec2-user/app/step3/zip/
    # 기존에 파일들이 있으면 덮어쓸지 결정
    overwrite: yes
# CodeDeploy에서 EC2 서버로 넘겨준 파일들은 모두 ec2-user 권한을 가지도록 함
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# CodeDeploy 배포 단계에서 실행 할 명령어를 지정
# Application Start 라는 단계에서 deploy.sh를 ec2-user 권한으로 실행
# timeout: 60으로 스크립트 실행 60초 이상 수행되면 실패(무한정 기다릴 수 없으니 시간 제한이 필수적)
hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - localtion: health.sh # 새 스프링부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user