# CodeDeploy 버전
# 프로젝트 버전이 아니므로 0.0 이외에 다른 버전을 사용하면 오류가 발생
version: 0.0
os: linux
files:
    # CodeDeploy에서 전달해준 파일 중 destination으로 이동 시킬 대상을 지정
    # 루트경로(/)의 경우 전체 파일
  - source: /
    # source에서 지정된 파일을 받을 위치
    # 이후 Jar 실행 등은 destination에서 옮긴 파일들로 진행
    destination: /home/ec2-user/app/step2/zip/
    # 기존에 파일들이 있으면 덮어쓸지 결정
    overwrite: yes